version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: learnquest-mongodb-dev
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: learnquest
    volumes:
      - mongodb_data_dev:/data/db
    networks:
      - learnquest-network

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: learnquest-backend-dev
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URL=mongodb://admin:password123@mongodb:27017/learnquest?authSource=admin
      - PYTHONUNBUFFERED=1
    depends_on:
      - mongodb
    networks:
      - learnquest-network
    volumes:
      - ./backend:/app
      - /app/venv

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: learnquest-frontend-dev
    restart: unless-stopped
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - backend
    networks:
      - learnquest-network
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  mongodb_data_dev:

networks:
  learnquest-network:
    driver: bridge
